import { useNavigate } from 'react-router-dom'
import { Y, BG, mono, display, serif } from '../components/tokens'

export default function TermsPage() {
  const navigate = useNavigate()
  return (
    <div style={{ background: BG, minHeight: '100vh', color: '#fff', fontFamily: mono }}>
      <nav style={{ borderBottom: '1px solid #1e1e1e', padding: '0 32px' }}>
        <div style={{ maxWidth: 800, margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: 60 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer' }} onClick={() => navigate('/')}>
            <div style={{ background: Y, color: '#111', fontSize: 10, fontWeight: 700, letterSpacing: 3, padding: '3px 8px', borderRadius: 3 }}>NYC</div>
            <span style={{ fontFamily: display, fontSize: 20, letterSpacing: 2 }}>APPEALWRITER</span>
          </div>
          <button onClick={() => navigate(-1)} style={{ background: 'transparent', border: '1px solid #333', borderRadius: 6, padding: '8px 14px', color: '#666', fontFamily: mono, fontSize: 11, letterSpacing: 1, cursor: 'pointer' }}>← Back</button>
        </div>
      </nav>

      <div style={{ maxWidth: 800, margin: '0 auto', padding: '60px 32px' }}>
        <div style={{ fontFamily: mono, fontSize: 11, color: Y, letterSpacing: 4, marginBottom: 14 }}>LEGAL</div>
        <h1 style={{ fontFamily: display, fontSize: 56, color: '#fff', letterSpacing: 2, marginBottom: 16, lineHeight: 1 }}>TERMS OF SERVICE</h1>
        <div style={{ fontFamily: mono, fontSize: 11, color: '#555', marginBottom: 48, letterSpacing: 1 }}>Effective Date: January 1, 2026</div>

        {[
          {
            title: 'Acceptance of Terms',
            body: `By accessing or using NYC Appeal Writer ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.`,
          },
          {
            title: 'Description of Service',
            body: `NYC Appeal Writer is an informational tool that generates template parking ticket appeal letters based on information you provide. The Service does not provide legal advice and does not create an attorney-client relationship.`,
          },
          {
            title: 'Not Legal Advice',
            body: `The letters generated by this Service are templates based on publicly available NYC traffic rules. They are not legal advice. You are solely responsible for reviewing your letter before submission and for the outcome of any appeal. We strongly recommend consulting a licensed attorney if your matter involves significant penalties or legal complexity.`,
          },
          {
            title: 'Pricing and Payments',
            body: `Your first appeal letter is free. Additional letters are priced at $9.99 per letter. An annual subscription ($39.99/year) provides unlimited letters. Payments are processed by Stripe. All sales are final unless required by law.\n\nAnnual subscriptions auto-renew annually. You may cancel at any time before the renewal date.`,
          },
          {
            title: 'User Responsibilities',
            body: `You agree to:\n\n• Provide accurate information when using the Service\n• Use generated letters only for legitimate personal parking appeal purposes\n• Not misrepresent facts in your appeal letters\n• Not use the Service to generate fraudulent or deceptive submissions\n\nWe reserve the right to terminate access for misuse.`,
          },
          {
            title: 'Intellectual Property',
            body: `The Service, including its design, copy, and generated letter templates, is owned by NYC Appeal Writer. You may use your generated letter for personal use. You may not reproduce, distribute, or commercialize the Service or its outputs without permission.`,
          },
          {
            title: 'Disclaimer of Warranties',
            body: `The Service is provided "as is" without warranties of any kind. We do not guarantee that your appeal will be successful. Success rates mentioned on the site are estimates based on general information and do not constitute a guarantee.`,
          },
          {
            title: 'Limitation of Liability',
            body: `To the maximum extent permitted by law, NYC Appeal Writer shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service, including any denied parking appeal.`,
          },
          {
            title: 'Governing Law',
            body: `These terms are governed by the laws of the State of New York. Any disputes shall be resolved in the courts of New York County, New York.`,
          },
          {
            title: 'Changes to Terms',
            body: `We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.`,
          },
          {
            title: 'Contact',
            body: `Questions about these Terms? Email: legal@nycappealwriter.com`,
          },
        ].map(s => (
          <div key={s.title} style={{ marginBottom: 40 }}>
            <h2 style={{ fontFamily: display, fontSize: 28, color: '#fff', letterSpacing: 1, marginBottom: 16 }}>{s.title}</h2>
            <p style={{ fontFamily: serif, fontSize: 17, color: '#777', lineHeight: 1.8, whiteSpace: 'pre-line' }}>{s.body}</p>
          </div>
        ))}
      </div>

      <footer style={{ borderTop: '1px solid #1a1a1a', padding: '24px 32px', textAlign: 'center' }}>
        <div style={{ fontFamily: mono, fontSize: 11, color: '#333', letterSpacing: 1 }}>
          © 2026 NYC Appeal Writer. All rights reserved.
        </div>
      </footer>
    </div>
  )
}
